// Code generated by go-swagger; DO NOT EDIT.

// Package apis Youtube API
//
//	Youtube API
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//	License: Apache 2.0 http://www.apache.org/licenses/LICENSE-2.0.html
//	Contact: <ridwan.rais2@gmail.com>
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package apis
